---
# Source: lma-addons/templates/grafana-dashboard/configmap-dashboards.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-calico-status
  namespace: lma
  labels:
    grafana_dashboard: "1"
    app: grafana
data:
  calico-Status.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 41,
      "iteration": 1668130181525,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "collapsed": false,
          "datasource": {
            "uid": "$datasource"
          },
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 11,
          "panels": [],
          "title": "Host status",
          "type": "row"
        },
        {
          "datasource": {
            "uid": "$datasource"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [
                {
                  "options": {
                    "0": {
                      "text": "NOK"
                    },
                    "1": {
                      "text": "OK"
                    }
                  },
                  "type": "value"
                },
                {
                  "options": {
                    "match": "null",
                    "result": {
                      "text": "No Data"
                    }
                  },
                  "type": "special"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "#FF7383",
                    "value": null
                  },
                  {
                    "color": "#56A64B",
                    "value": 1
                  },
                  {
                    "color": "#FFCB7D",
                    "value": 2
                  }
                ]
              },
              "unit": "none"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 2,
            "w": 6,
            "x": 0,
            "y": 1
          },
          "id": 2,
          "links": [],
          "maxDataPoints": 100,
          "options": {
            "colorMode": "background",
            "graphMode": "none",
            "justifyMode": "auto",
            "orientation": "horizontal",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "pluginVersion": "8.3.3",
          "repeat": "hosts",
          "repeatDirection": "h",
          "targets": [
            {
              "expr": "kube_pod_info{job=\"kube-state-metrics\", created_by_name=\"calico-node\", node=\"$hosts\", taco_cluster=\"$taco_cluster\"}",
              "format": "time_series",
              "instant": false,
              "intervalFactor": 1,
              "refId": "A"
            }
          ],
          "title": "Calico@${hosts}",
          "type": "stat"
        },
        {
          "collapsed": false,
          "datasource": {
            "uid": "$datasource"
          },
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 5
          },
          "id": 22,
          "panels": [],
          "title": "felix Control Plane",
          "type": "row"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": {
            "uid": "$datasource"
          },
          "description": "",
          "fieldConfig": {
            "defaults": {
              "links": []
            },
            "overrides": []
          },
          "fill": 0,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 6
          },
          "hiddenSeries": false,
          "id": 20,
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": true,
            "hideEmpty": false,
            "max": true,
            "min": false,
            "rightSide": true,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "8.3.3",
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "alloc rate",
              "yaxis": 2
            }
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "bytes allocated ({{pod}})",
              "refId": "A"
            },
            {
              "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\"}[5m])",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "alloc rate",
              "refId": "B"
            },
            {
              "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", taco_cluster=\"$taco_cluster\"}",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "stack inuse ({{pod}})",
              "refId": "C"
            },
            {
              "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", taco_cluster=\"$taco_cluster\"}",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "heap inuse ({{pod}})",
              "refId": "D"
            }
          ],
          "thresholds": [],
          "timeRegions": [],
          "title": "go memstats",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "decbytes",
              "label": "",
              "logBase": 1,
              "min": "0",
              "show": true
            },
            {
              "format": "Bps",
              "logBase": 1,
              "min": "0",
              "show": true
            }
          ],
          "yaxis": {
            "align": false
          }
        }
      ],
      "refresh": "5s",
      "schemaVersion": 34,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "Prometheus",
              "value": "Prometheus"
            },
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "prometheus",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "hide": 2,
            "name": "hostCount",
            "query": "${VAR_HOSTCOUNT}",
            "skipUrlSync": false,
            "type": "constant"
          },
          {
            "hide": 2,
            "name": "rowCount",
            "query": "${VAR_ROWCOUNT}",
            "skipUrlSync": false,
            "type": "constant"
          },
          {
            "current": {
              "selected": false,
              "text": "siim-dev",
              "value": "siim-dev"
            },
            "datasource": {
              "uid": "$datasource"
            },
            "definition": "label_values(up, taco_cluster)",
            "hide": 0,
            "includeAll": false,
            "label": "taco_cluster",
            "multi": false,
            "name": "taco_cluster",
            "options": [],
            "query": {
              "query": "label_values(up, taco_cluster)",
              "refId": "Prometheus-taco_cluster-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          },
          {
            "allValue": ".*",
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": {
              "uid": "$datasource"
            },
            "definition": "label_values(kube_pod_info{created_by_name=\"calico-node\", taco_cluster=\"$taco_cluster\"}, node)",
            "hide": 2,
            "includeAll": true,
            "multi": true,
            "name": "hosts",
            "options": [],
            "query": {
              "query": "label_values(kube_pod_info{created_by_name=\"calico-node\", taco_cluster=\"$taco_cluster\"}, node)",
              "refId": "Prometheus-hosts-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          },
          {
            "current": {
              "selected": false,
              "text": "alerted-log-exporter",
              "value": "alerted-log-exporter"
            },
            "datasource": {
              "uid": "$datasource"
            },
            "definition": "label_values(go_memstats_alloc_bytes{taco_cluster=\"$taco_cluster\"},job)",
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "job",
            "options": [],
            "query": {
              "query": "label_values(go_memstats_alloc_bytes{taco_cluster=\"$taco_cluster\"},job)",
              "refId": "Prometheus-job-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "",
      "title": "calico",
      "uid": "taco-calicostatus",
      "version": 1,
      "weekStart": ""
    }
